#!/usr/bin/env python
#
#    Copyright (c) 2011-2013 Anton Tyurin <noxiouz@yandex.ru>
#    Copyright (c) 2011-2013 Other contributors as noted in the AUTHORS file.
#
#    This file is part of Cocaine.
#
#    Cocaine is free software; you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published
#    by the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    Cocaine is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from tornado import web
from tornado.ioloop import IOLoop
from tornado.options import options

from flow.utils.route import Route
from flow.utils.storage import Storage
from flow.utils.daemon import Daemon
#import utils.options  # some tornado's options are defined here
from flow.utils.options import actions

from flow.views import *

SETTINGS = {
    "cookie_secret": options.SECRET_KEY,
    "debug": True,
    "login_url": "/login"
}

def main():
    Storage()
    app = web.Application(Route.routes(), static_path="./", **SETTINGS)
    app.listen(8080)
    IOLoop.instance().start()

if __name__ == "__main__":
    if options.daemon:
        d = Daemon(options.pidfile)
        if "start" in actions:
            d.run = main
            d.start()
        elif "stop" in actions:
            d.stop()
        elif "restart" in actions:
            d.run = main
            d.restart()
        elif "status" in actions:
            d.status()
        else:
            print("start|stop|restart|status")
            exit(0)
    else:
        main()
